/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centreimagerie;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author TAHAR
 */
public class AdddoctorR extends javax.swing.JFrame {
    Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;


    /**
     * Creates new form AdddoctorR
     */
    public AdddoctorR() {
        initComponents();
        setExtendedState(AdddoctorR.MAXIMIZED_BOTH);
        dt();
        showtable();
       
    }
    public void dt()
    {
    Date d = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String dd=sdf.format(d);
    ddate.setText(dd);
    }
     public void setRecords(){
        DefaultTableModel model = (DefaultTableModel) tabledoctor.getModel();
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    PreparedStatement pst = con.prepareStatement("SELECT * FROM doctor");
    ResultSet rs = pst.executeQuery();
    
    while(rs.next())
    {
    String id = rs.getString("ID");
    String nom = rs.getString("F_name");
    String bdate = rs.getString("B_date");
    String genre = rs.getString("Genre");
    String adate = rs.getString("Add_date");
    String spec = rs.getString("Specialty");
    String phn = rs.getString("Phone");
    String add = rs.getString("Address");
    Object[] obj = {id, nom, bdate, genre,spec,adate, phn, add};
    model = (DefaultTableModel)tabledoctor.getModel();
    model.addRow(obj);
    }
    
    } catch (SQLException ex) {
        Logger.getLogger(RegistrationR.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
     
     public void search(String str){
        DefaultTableModel model = (DefaultTableModel) tabledoctor.getModel();
    model = (DefaultTableModel) tabledoctor.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    tabledoctor.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        cnaspic = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ddate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateadd = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combospecia = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btsreset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        combogenre = new javax.swing.JComboBox<>();
        search = new javax.swing.JTextField();
        txtbdate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledoctor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1373, 710));
        setMinimumSize(new java.awt.Dimension(1373, 710));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 248, 240));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 48, 73));
        jPanel3.setMaximumSize(new java.awt.Dimension(185, 710));
        jPanel3.setMinimumSize(new java.awt.Dimension(185, 710));
        jPanel3.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 48, 73));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 248, 240));
        jButton2.setText("Log out");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(30, 630, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 48, 73));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 248, 240));
        jButton3.setText("Home page");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(30, 580, 130, 40);

        jButton4.setBackground(new java.awt.Color(0, 48, 73));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 248, 240));
        jButton4.setText("Registration");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(30, 130, 130, 40);

        jButton5.setBackground(new java.awt.Color(0, 48, 73));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 248, 240));
        jButton5.setText("Patients list");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(30, 180, 130, 40);

        jButton6.setBackground(new java.awt.Color(0, 48, 73));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 248, 240));
        jButton6.setText("Add doctors");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(30, 230, 130, 40);

        jButton7.setBackground(new java.awt.Color(0, 48, 73));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 248, 240));
        jButton7.setText("Doctors list");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(30, 280, 130, 40);

        jButton8.setBackground(new java.awt.Color(0, 48, 73));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 248, 240));
        jButton8.setText("Radios ");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(30, 330, 130, 40);

        cnaspic.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\aaa.png")); // NOI18N
        jPanel3.add(cnaspic);
        cnaspic.setBounds(20, 20, 130, 80);

        jButton9.setBackground(new java.awt.Color(0, 48, 73));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 248, 240));
        jButton9.setText("Technicians list");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(30, 430, 130, 40);

        jButton10.setBackground(new java.awt.Color(0, 48, 73));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 248, 240));
        jButton10.setText("Add technicians");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(30, 380, 130, 40);

        jButton11.setBackground(new java.awt.Color(0, 48, 73));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 248, 240));
        jButton11.setText("Appointment ");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(30, 480, 130, 40);

        jButton1.setBackground(new java.awt.Color(0, 48, 73));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 248, 240));
        jButton1.setText("Appointments list");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(30, 530, 130, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 185, 710);

        jPanel2.setBackground(new java.awt.Color(0, 48, 73));
        jPanel2.setMaximumSize(new java.awt.Dimension(1380, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(1380, 40));
        jPanel2.setLayout(null);

        ddate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ddate.setForeground(new java.awt.Color(255, 248, 240));
        jPanel2.add(ddate);
        ddate.setBounds(1280, 0, 90, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 248, 240));
        jLabel1.setText("Doctor's registration");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(710, 0, 220, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1380, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 80, 50, 22);

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        jPanel1.add(txtid);
        txtid.setBounds(370, 80, 190, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText(" Full name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 140, 100, 22);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(370, 140, 190, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText(" Birth date :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 200, 100, 22);
        jPanel1.add(dateadd);
        dateadd.setBounds(1020, 80, 190, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("   Genre :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 260, 80, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText(" Add date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(910, 80, 90, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("   Specialty : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(900, 130, 110, 20);

        combospecia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Specialty", "Generalist.", "Radiologist." }));
        jPanel1.add(combospecia);
        combospecia.setBounds(1020, 130, 190, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText(" Phone :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(930, 190, 70, 14);

        txtphone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });
        jPanel1.add(txtphone);
        txtphone.setBounds(1020, 190, 190, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText(" Address :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(920, 250, 80, 14);

        txtadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtadd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtadd);
        txtadd.setBounds(1020, 250, 190, 30);

        btnadd.setBackground(new java.awt.Color(0, 48, 73));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 248, 240));
        btnadd.setText("Add");
        btnadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd);
        btnadd.setBounds(260, 360, 130, 40);

        btnupdate.setBackground(new java.awt.Color(0, 48, 73));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 248, 240));
        btnupdate.setText("Update");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(550, 360, 130, 40);

        btndelete.setBackground(new java.awt.Color(0, 48, 73));
        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 248, 240));
        btndelete.setText("Delete");
        btndelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(860, 360, 130, 40);

        btsreset.setBackground(new java.awt.Color(0, 48, 73));
        btsreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btsreset.setForeground(new java.awt.Color(255, 248, 240));
        btsreset.setText("Reset");
        btsreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btsreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsresetActionPerformed(evt);
            }
        });
        jPanel1.add(btsreset);
        btsreset.setBounds(1150, 360, 130, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Search :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(500, 450, 62, 20);

        combogenre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combogenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Male", "Female", " " }));
        combogenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenreActionPerformed(evt);
            }
        });
        jPanel1.add(combogenre);
        combogenre.setBounds(370, 260, 190, 30);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(580, 440, 440, 30);
        jPanel1.add(txtbdate);
        txtbdate.setBounds(370, 200, 190, 30);

        tabledoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "F_name", "B_date", "Genre", "Add_date", "Specialty", "Phone", "Address"
            }
        ));
        tabledoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledoctorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledoctor);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 510, 1140, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login out = new Login();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        RegistrationR go = new RegistrationR();
        go.setLocationRelativeTo(null);
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PatientlistR list = new PatientlistR();
        list.setLocationRelativeTo(null);
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DoctorlistR out = new DoctorlistR();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        RadiolistR out = new RadiolistR();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        homer out = new homer();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void combogenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combogenreActionPerformed

    private void btsresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsresetActionPerformed
        // Reset code:
        txtid.setText("");
        txtname.setText("");
        txtbdate.setDateFormatString("");
        combogenre.setSelectedItem("Choose");
        dateadd.setDateFormatString("");
        combospecia.setSelectedItem("Specialty");
        txtphone.setText("");
        txtadd.setText("");
    }//GEN-LAST:event_btsresetActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // add code:
        String id = txtid.getText().toString();
        String name = txtname.getText();
        String bd = txtbdate.getDateFormatString();
        String gen = combogenre.getSelectedItem().toString();
        String ad = dateadd.getDateFormatString();
        String sp = combospecia.getSelectedItem().toString();
        String ph = txtphone.getText().toString();
        String add = txtadd.getText();
        if(id.equals("")||name.equals("")||bd.equals("")||gen.equals("Choose")||ad.equals("")||sp.equals("Specialty")||ph.equals("")||add.equals(""))
        {
        JOptionPane.showMessageDialog(rootPane, "Some fields are empty check again", "ERROR",1);
        }
        else {
        Date selectedDate = txtbdate.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate1 = dateFormat.format(selectedDate);
        
         Date selectedDate2 = dateadd.getDate();
        SimpleDateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate2 = dateFormat2.format(selectedDate2);
        
        try{
        String sql = "INSERT INTO doctor"
                +"(ID, F_name, B_date, Genre,Add_date, Specialty, Phone, Address)"
                +"VALUES (?,?,?,?,?,?,?,?)";
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
        pst = con.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(txtid.getText()));
        pst.setString(2, txtname.getText());
        pst.setString(3, formattedDate1);
        pst.setString(4, combogenre.getSelectedItem().toString());
        pst.setString(5, formattedDate2);
        pst.setString(6, combospecia.getSelectedItem().toString());
        pst.setInt(7, Integer.parseInt(txtphone.getText()));
        pst.setString(8, txtadd.getText());
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "ADD successfully!");
        
        
        
        } catch (HeadlessException | NumberFormatException | SQLException ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
         
      showtable(); 
      txtid.setText("");
        txtname.setText("");
        txtbdate.setDateFormatString("");
        combogenre.setSelectedItem("Choose");
         dateadd.setDateFormatString("");
         combospecia.setSelectedItem("Specialty");
        txtphone.setText("");
        txtadd.setText("");
      
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // Update code:
        DefaultTableModel model = (DefaultTableModel) tabledoctor.getModel();
        int row = tabledoctor.getSelectedRow();
        
        
        try{
        String sql = "UPDATE doctor SET F_name=?,B_date=?,Genre=?,Add_date=?, Specialty=?,Phone=?,Address=? WHERE ID=?";
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
        pst = con.prepareStatement(sql);
        pst.setInt(8, Integer.parseInt(txtid.getText()));
        pst.setString(1, txtname.getText());
        pst.setString(2, txtbdate.getDateFormatString());
        pst.setString(3, combogenre.getSelectedItem().toString());
        pst.setString(4, dateadd.getDateFormatString());
        pst.setString(5, combospecia.getSelectedItem().toString());
        pst.setInt(6, Integer.parseInt(txtphone.getText()));
        pst.setString(7, txtadd.getText());
       
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "UPDATED successfully!");
        
        
        
        } catch (HeadlessException | NumberFormatException | SQLException ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
         
      showtable(); 
      txtid.setText("");
        txtname.setText("");
        txtbdate.setDateFormatString("");
        combogenre.setSelectedItem("Choose");
         dateadd.setDateFormatString("");
         combospecia.setSelectedItem("Specialty");
        txtphone.setText("");
        txtadd.setText("");
      
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tabledoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledoctorMouseClicked
        // Mouseclick code:
         DefaultTableModel model = (DefaultTableModel) tabledoctor.getModel();
        int selectedRowIndex = tabledoctor.getSelectedRow();
        txtid.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtbdate.setDateFormatString(model.getValueAt(selectedRowIndex, 2).toString());
        combogenre.setSelectedItem(model.getValueAt(selectedRowIndex, 3).toString());
        dateadd.setDateFormatString(model.getValueAt(selectedRowIndex, 4).toString());
        combospecia.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString());
        txtphone.setText(model.getValueAt(selectedRowIndex, 6).toString());
        txtadd.setText(model.getValueAt(selectedRowIndex, 7).toString());
        
    }//GEN-LAST:event_tabledoctorMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // Delete code:
        int row = tabledoctor.getSelectedRow();
        String cell = tabledoctor.getModel().getValueAt(row, 0).toString();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
         if (choice == JOptionPane.YES_OPTION) {
        String sql= "DELETE FROM doctor WHERE ID = " +cell;
        try{
        pst = con.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "DELETED succesfully");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        showtable();
        txtid.setText("");
        txtname.setText("");
        txtbdate.setDateFormatString("");
        combogenre.setSelectedItem("Choose");
         dateadd.setDateFormatString("");
         combospecia.setSelectedItem("Specialty");
        txtphone.setText("");
        txtadd.setText("");
         }
         else {
            System.out.println("Deletion canceled");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String searchString = search.getText();
        search(searchString);
    }//GEN-LAST:event_searchKeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        TechlistR out = new TechlistR();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        AddtechnicianR out = new AddtechnicianR();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // Characters only:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
        txtname.setEditable(true);
        }
        else{
        
        txtname.setEditable(false);}
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // Numbers only:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
        txtid.setEditable(false);
        }
        else{
        txtid.setEditable(true);
        }
    }//GEN-LAST:event_txtidKeyPressed

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // Phone code:
        String pn = txtphone.getText();
        int lenght = pn.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
        if(lenght<10)
        {
        txtphone.setEditable(true);
        }
        else{
        txtphone.setEditable(false);
        }
        }
        else{
        if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
        {txtphone.setEditable(true);}
        else{txtphone.setEditable(false);}
        }
    }//GEN-LAST:event_txtphoneKeyPressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        AppointmentR ap = new AppointmentR();
        ap.setLocationRelativeTo(null);
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AppointmentlistR out = new AppointmentlistR();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

     public void showtable(){
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    String sql = "SELECT * FROM doctor";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    tabledoctor.setModel(DbUtils.resultSetToTableModel(rs));
    
    
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null, ex);
    }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdddoctorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdddoctorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdddoctorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdddoctorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdddoctorR fenetre = new AdddoctorR();
               //set titel
        fenetre.setTitle("Add doctor");
        //nous demandons mtn a notre objet de se positionner au centre
        fenetre.setLocationRelativeTo(null);
        //termine le processus lorsqu'on clique sur la croix rouge
        fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenetre.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btsreset;
    private javax.swing.JLabel cnaspic;
    private javax.swing.JComboBox<String> combogenre;
    private javax.swing.JComboBox<String> combospecia;
    private com.toedter.calendar.JDateChooser dateadd;
    private javax.swing.JLabel ddate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTable tabledoctor;
    private javax.swing.JTextField txtadd;
    private com.toedter.calendar.JDateChooser txtbdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
