/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centreimagerie;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author TAHAR
 */
public class AddpaneT extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form AddpaneT
     */
    public AddpaneT() {
        initComponents();
        setExtendedState(AddpaneT.MAXIMIZED_BOTH);
        dt();
        showtable();
    }
    public void dt()
    {
    Date d = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String dd=sdf.format(d);
    datet.setText(dd);
    }
    public void setRecords(){
        DefaultTableModel model = (DefaultTableModel) tablepane.getModel();
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    PreparedStatement pst = con.prepareStatement("SELECT * FROM pane");
    ResultSet rs = pst.executeQuery();
    
    while(rs.next())
    {
    String id = rs.getString("Number");
    String nom = rs.getString("Machine_Name");
    String tid = rs.getString("Tech_ID");
    String tname = rs.getString("Tech_Name");
    String pa = rs.getString("Pane");
    String adate = rs.getString("datepane");
    String descr= rs.getString("Description");
    
    Object[] obj = {id, nom,tid,tname,pa, adate, descr};
    model = (DefaultTableModel)tablepane.getModel();
    model.addRow(obj);
    }
    
    } catch (SQLException ex) {
        Logger.getLogger(RegistrationR.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
     
     public void search(String str){
        DefaultTableModel model = (DefaultTableModel) tablepane.getModel();
    model = (DefaultTableModel) tablepane.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    tablepane.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cnaspic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        datet = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pane = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        datepane = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btsreset = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepane = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1373, 710));
        setMinimumSize(new java.awt.Dimension(1373, 710));
        setPreferredSize(new java.awt.Dimension(1373, 710));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 48, 73));
        jPanel1.setMaximumSize(new java.awt.Dimension(185, 710));
        jPanel1.setMinimumSize(new java.awt.Dimension(185, 710));
        jPanel1.setLayout(null);

        jButton5.setBackground(new java.awt.Color(0, 48, 73));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 248, 240));
        jButton5.setText("Technicians list");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 180, 130, 40);

        jButton4.setBackground(new java.awt.Color(0, 48, 73));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 248, 240));
        jButton4.setText("Add technician");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 130, 130, 40);

        jButton6.setBackground(new java.awt.Color(0, 48, 73));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 248, 240));
        jButton6.setText("Add machine");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(30, 230, 130, 40);

        jButton7.setBackground(new java.awt.Color(0, 48, 73));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 248, 240));
        jButton7.setText("Machines list");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(30, 280, 130, 40);

        jButton8.setBackground(new java.awt.Color(0, 48, 73));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 248, 240));
        jButton8.setText("Add breakdown");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(30, 330, 130, 40);

        jButton1.setBackground(new java.awt.Color(0, 48, 73));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 248, 240));
        jButton1.setText("Breakdowns list");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 380, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 48, 73));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 248, 240));
        jButton3.setText("Home page");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 430, 130, 40);

        jButton2.setBackground(new java.awt.Color(0, 48, 73));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 248, 240));
        jButton2.setText("Log out");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 480, 130, 40);

        cnaspic.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\aaa.png")); // NOI18N
        jPanel1.add(cnaspic);
        cnaspic.setBounds(20, 20, 130, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 185, 710);

        jPanel2.setBackground(new java.awt.Color(0, 48, 73));
        jPanel2.setMaximumSize(new java.awt.Dimension(1380, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(1380, 40));
        jPanel2.setLayout(null);

        datet.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        datet.setForeground(new java.awt.Color(255, 248, 240));
        jPanel2.add(datet);
        datet.setBounds(1280, 0, 90, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 248, 240));
        jLabel1.setText("Add breakdown");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(680, 0, 170, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1380, 40);

        jPanel3.setBackground(new java.awt.Color(255, 248, 240));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Technician Name :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(260, 270, 150, 22);

        txttname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txttname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttnameActionPerformed(evt);
            }
        });
        txttname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttnameKeyPressed(evt);
            }
        });
        jPanel3.add(txttname);
        txttname.setBounds(430, 270, 190, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Machine name :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(280, 140, 130, 22);

        txtmname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtmname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtmname);
        txtmname.setBounds(430, 140, 190, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText(" Breakdown :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(300, 330, 110, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Technician ID :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(290, 210, 130, 22);

        pane.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneActionPerformed(evt);
            }
        });
        jPanel3.add(pane);
        pane.setBounds(430, 330, 190, 30);

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        jPanel3.add(txtid);
        txtid.setBounds(430, 210, 190, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("N° :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(370, 80, 50, 22);

        desc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        desc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        jPanel3.add(desc);
        desc.setBounds(1000, 130, 350, 240);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Description :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(870, 150, 100, 17);
        jPanel3.add(datepane);
        datepane.setBounds(1000, 80, 190, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText(" Breakdown date :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(830, 90, 150, 17);

        txtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnActionPerformed(evt);
            }
        });
        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnKeyPressed(evt);
            }
        });
        jPanel3.add(txtn);
        txtn.setBounds(430, 80, 190, 30);

        btnadd.setBackground(new java.awt.Color(0, 48, 73));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 248, 240));
        btnadd.setText("Add");
        btnadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnadd);
        btnadd.setBounds(260, 400, 130, 40);

        btnupdate.setBackground(new java.awt.Color(0, 48, 73));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 248, 240));
        btnupdate.setText("Update");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate);
        btnupdate.setBounds(560, 400, 130, 40);

        btndelete.setBackground(new java.awt.Color(0, 48, 73));
        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 248, 240));
        btndelete.setText("Delete");
        btndelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btndelete);
        btndelete.setBounds(860, 400, 130, 40);

        btsreset.setBackground(new java.awt.Color(0, 48, 73));
        btsreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btsreset.setForeground(new java.awt.Color(255, 248, 240));
        btsreset.setText("Reset");
        btsreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btsreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsresetActionPerformed(evt);
            }
        });
        jPanel3.add(btsreset);
        btsreset.setBounds(1160, 400, 130, 40);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(590, 470, 440, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Search :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(490, 470, 62, 20);

        tablepane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Machine_Name", "Tech_ID", "Tech_Name", "Pane", "Pane_Date", "Description"
            }
        ));
        tablepane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepaneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepane);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(210, 510, 1140, 190);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1370, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TechlistT out = new TechlistT();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AddtechnicianT out = new AddtechnicianT();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AddmachineT out = new AddmachineT();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MachinelistT out = new MachinelistT();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        AddpaneT out = new AddpaneT();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PanelistT out = new PanelistT();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login out = new Login();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txttnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttnameActionPerformed

    private void txtmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnameActionPerformed

    private void paneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paneActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String n= txtn.getText().toString();
        String name = txtmname.getText();
        String id = txtid.getText().toString();
        String tn = txttname.getText();
        String p = pane.getText();
        String date = datepane.getDateFormatString();
        String ds = desc.getText();
        if(n.equals("")||name.equals("")||id.equals("")||tn.equals("")||p.equals("")||date.equals("")||ds.equals(""))
        {
        JOptionPane.showMessageDialog(rootPane, "Some fields are empty check again", "ERROR",1);
        }
        else{
        Date selectedDate = datepane.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate1 = dateFormat.format(selectedDate);

        try{
            String sql = "INSERT INTO pane"
            +"(Number, Machine_Name, Tech_ID, Tech_Name, Pane, Pane_Date, Description)"
            +"VALUES (?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
            pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txtn.getText()));
            pst.setString(2, txtmname.getText());
            pst.setInt(3, Integer.parseInt(txtid.getText()));
            pst.setString(4, txttname.getText());
            pst.setString(5, pane.getText());
            pst.setString(6, formattedDate1);
            pst.setString(7, desc.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "ADD successfully!");

        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        showtable();
        txtn.setText("");
        txtmname.setText("");
        txtid.setText("");
        txttname.setText("");
        pane.setText("");
       datepane.setDateFormatString("");
       desc.setText("");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablepane.getModel();
        int row = tablepane.getSelectedRow();

        try{
            String sql = "UPDATE pane SET  Machine_Name=?, Tech_ID=?, Tech_Name=?, Pane=?, Pane_Date=?, Description=? WHERE Number=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
            pst = con.prepareStatement(sql);
            pst.setInt(7, Integer.parseInt(txtn.getText()));
            pst.setString(1, txtmname.getText());
            pst.setInt(2, Integer.parseInt(txtid.getText()));
            pst.setString(3, txttname.getText());
            pst.setString(4, pane.getText());
            pst.setString(5, datepane.getDateFormatString());
            pst.setString(6, desc.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "UPDATED successfully!");

        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        showtable();
       txtn.setText("");
        txtmname.setText("");
        txtid.setText("");
        txttname.setText("");
        pane.setText("");
       datepane.setDateFormatString("");
       desc.setText("");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int row = tablepane.getSelectedRow();
        String cell = tablepane.getModel().getValueAt(row, 0).toString();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (choice == JOptionPane.YES_OPTION) {
        String sql= "DELETE FROM pane WHERE Number = " +cell;
        try{
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "DELETED succesfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        showtable();
        txtn.setText("");
        txtmname.setText("");
        txtid.setText("");
        txttname.setText("");
        pane.setText("");
       datepane.setDateFormatString("");
       desc.setText("");
        }
        else {
            System.out.println("Deletion canceled");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btsresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsresetActionPerformed
        // TODO add your handling code here:
        txtn.setText("");
        txtmname.setText("");
        txtid.setText("");
        txttname.setText("");
        pane.setText("");
       datepane.setDateFormatString("");
       desc.setText("");
    }//GEN-LAST:event_btsresetActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String searchString = search.getText();
        search(searchString);
    }//GEN-LAST:event_searchKeyReleased

    private void tablepaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepaneMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablepane.getModel();
        int selectedRowIndex = tablepane.getSelectedRow();
        txtn.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtmname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtid.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txttname.setText(model.getValueAt(selectedRowIndex, 3).toString());
        pane.setText(model.getValueAt(selectedRowIndex, 4).toString());
        datepane.setDateFormatString(model.getValueAt(selectedRowIndex, 5).toString());
        desc.setText(model.getValueAt(selectedRowIndex, 6).toString());
        
    }//GEN-LAST:event_tablepaneMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        homet out = new homet();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
        txttname.setEditable(true);
        }
        else{
        
        txttname.setEditable(false);}
    }//GEN-LAST:event_txttnameKeyPressed

    private void txtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
        txtn.setEditable(false);
        }
        else{
        txtn.setEditable(true);
        }
    }//GEN-LAST:event_txtnKeyPressed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
        txtid.setEditable(false);
        }
        else{
        txtid.setEditable(true);
        }
    }//GEN-LAST:event_txtidKeyPressed
 public void showtable(){
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    String sql = "SELECT * FROM pane";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    tablepane.setModel(DbUtils.resultSetToTableModel(rs));
    
    
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null, ex);
    }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddpaneT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddpaneT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddpaneT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddpaneT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 AddpaneT fenetre = new AddpaneT();
               //set titel
        fenetre.setTitle("Add breakdown");
        //nous demandons mtn a notre objet de se positionner au centre
        fenetre.setLocationRelativeTo(null);
        //termine le processus lorsqu'on clique sur la croix rouge
        fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenetre.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btsreset;
    private javax.swing.JLabel cnaspic;
    private com.toedter.calendar.JDateChooser datepane;
    private javax.swing.JLabel datet;
    private javax.swing.JTextField desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pane;
    private javax.swing.JTextField search;
    private javax.swing.JTable tablepane;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txttname;
    // End of variables declaration//GEN-END:variables
}
