/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centreimagerie;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author TAHAR
 */
public class ConsultationD extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form ConsultationD
     */
    public ConsultationD() {
        initComponents();
        dt();
        showtable();
        showtable2();
    }
 public void dt()
    {
    Date d = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String dd=sdf.format(d);
    dated.setText(dd);
    }
    public void setRecords(){
        DefaultTableModel model = (DefaultTableModel) tablepatient.getModel();
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    PreparedStatement pst = con.prepareStatement("SELECT * FROM patient");
    ResultSet rs = pst.executeQuery();
    
    while(rs.next())
    {
    String id = rs.getString("ID");
    String ass= rs.getString("N_ass");
    String nom = rs.getString("F_name");
    String bdate = rs.getString("B_date");
    String genre = rs.getString("Genre");
    String phn = rs.getString("Phone");
    String add = rs.getString("Address");
    String rd = rs.getString("Radio");
    String visit = rs.getString("Visit_D");
    String pour = rs.getString("Pourcentage"); 
    String pri = rs.getString("Price");
    String doc = rs.getString("Doctor");
    String radiolo = rs.getString("Radiologiste");
    Object[] obj = {id,ass, nom, bdate, genre, phn, add,rd, visit, pour, pri, doc, radiolo};
    model = (DefaultTableModel)tablepatient.getModel();
    model.addRow(obj);
    }
    
    } catch (SQLException ex) {
        Logger.getLogger(RegistrationR.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }
    public void search(String str){
        DefaultTableModel model = (DefaultTableModel) tablepatient.getModel();
    model = (DefaultTableModel) tablepatient.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    tablepatient.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    
    }
    
     public void setRecords2(){
        DefaultTableModel model = (DefaultTableModel) tablecon.getModel();
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    PreparedStatement pst = con.prepareStatement("SELECT * FROM consult");
    ResultSet rs = pst.executeQuery();
    
    while(rs.next())
    {
    String id = rs.getString("ID");
    String ass= rs.getString("N_ass");
    String nom = rs.getString("F_name");
    String bdate = rs.getString("B_date");
    String genre = rs.getString("Genre");
    String phn = rs.getString("Phone");
    String add = rs.getString("Address");
    String rd = rs.getString("Radio");
    String visit = rs.getString("Visit_D");
    String doc = rs.getString("Doctor");
    String radiolo = rs.getString("Radiologiste");
    String nt = rs.getString("Note");
    Object[] obj = {id,ass, nom, bdate, genre, phn, add,rd, visit, doc, radiolo,nt};
    model = (DefaultTableModel)tablepatient.getModel();
    model.addRow(obj);
    }
    
    } catch (SQLException ex) {
        Logger.getLogger(RegistrationR.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }
    public void search2(String str){
        DefaultTableModel model = (DefaultTableModel) tablecon.getModel();
    model = (DefaultTableModel) tablecon.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    tablecon.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cnaspic = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dated = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtvdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboradiologiste = new javax.swing.JComboBox<>();
        txtid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboradio = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        combogenre = new javax.swing.JComboBox<>();
        btnreset = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepatient = new javax.swing.JTable();
        combodoc = new javax.swing.JComboBox<>();
        txtbdate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtass = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        note = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablecon = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtpour = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        search1 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1370, 710));
        setMinimumSize(new java.awt.Dimension(1370, 710));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 48, 73));
        jPanel1.setMaximumSize(new java.awt.Dimension(185, 710));
        jPanel1.setMinimumSize(new java.awt.Dimension(185, 710));
        jPanel1.setLayout(null);

        jButton4.setBackground(new java.awt.Color(0, 48, 73));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 248, 240));
        jButton4.setText("Registration");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 130, 130, 40);

        jButton5.setBackground(new java.awt.Color(0, 48, 73));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 248, 240));
        jButton5.setText("Patients list");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 180, 130, 40);

        jButton6.setBackground(new java.awt.Color(0, 48, 73));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 248, 240));
        jButton6.setText("Add doctor");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(30, 230, 130, 40);

        jButton7.setBackground(new java.awt.Color(0, 48, 73));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 248, 240));
        jButton7.setText("Doctors list");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(30, 280, 130, 40);

        jButton8.setBackground(new java.awt.Color(0, 48, 73));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 248, 240));
        jButton8.setText("Radios");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(30, 330, 130, 40);

        jButton1.setBackground(new java.awt.Color(0, 48, 73));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 248, 240));
        jButton1.setText("Prescription");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 380, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 48, 73));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 248, 240));
        jButton3.setText("Home page");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 480, 130, 40);

        jButton2.setBackground(new java.awt.Color(0, 48, 73));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 248, 240));
        jButton2.setText("Log out");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 530, 130, 40);

        cnaspic.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\aaa.png")); // NOI18N
        jPanel1.add(cnaspic);
        cnaspic.setBounds(20, 20, 130, 80);

        jButton9.setBackground(new java.awt.Color(0, 48, 73));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 248, 240));
        jButton9.setText("Consultation");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(30, 430, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 185, 710);

        jPanel2.setBackground(new java.awt.Color(0, 48, 73));
        jPanel2.setLayout(null);

        dated.setBackground(new java.awt.Color(255, 248, 240));
        dated.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dated.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(dated);
        dated.setBounds(1280, 0, 90, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 248, 240));
        jLabel15.setText("Consultation");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(720, 0, 170, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1380, 40);

        jPanel3.setBackground(new java.awt.Color(255, 248, 240));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText(" ID :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(250, 230, 50, 22);

        txtadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtadd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(txtadd);
        txtadd.setBounds(680, 330, 190, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("  Full name :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(200, 330, 100, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText(" Birth date :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(200, 380, 100, 22);
        jPanel3.add(txtvdate);
        txtvdate.setBounds(680, 380, 190, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("   Genre :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(590, 230, 80, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("   Phone : ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(590, 280, 80, 22);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        jPanel3.add(txtname);
        txtname.setBounds(310, 330, 190, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("  Address :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(580, 330, 90, 22);

        txtphone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphoneKeyPressed(evt);
            }
        });
        jPanel3.add(txtphone);
        txtphone.setBounds(680, 280, 190, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText(" Visit date :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(580, 380, 90, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("  Radio : ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(980, 230, 80, 20);

        comboradiologiste.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        comboradiologiste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radiologiste", "Radiologiste 1", "Radiologiste 2", "Radiologiste 3", "Radiologiste 4", " " }));
        jPanel3.add(comboradiologiste);
        comboradiologiste.setBounds(1070, 330, 190, 30);

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        jPanel3.add(txtid);
        txtid.setBounds(310, 230, 190, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("   Doctor :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(970, 290, 80, 17);

        comboradio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Radio", "Scanner", "MRI", "Dental panoramic", "Echography", " " }));
        jPanel3.add(comboradio);
        comboradio.setBounds(1070, 230, 190, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText(" Note :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(1000, 380, 60, 22);

        combogenre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combogenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Male", "Female", " " }));
        combogenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenreActionPerformed(evt);
            }
        });
        jPanel3.add(combogenre);
        combogenre.setBounds(680, 230, 190, 30);

        btnreset.setBackground(new java.awt.Color(0, 48, 73));
        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 248, 240));
        btnreset.setText("Reset");
        btnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel3.add(btnreset);
        btnreset.setBounds(1120, 490, 130, 40);

        btnadd.setBackground(new java.awt.Color(0, 48, 73));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 248, 240));
        btnadd.setText("Add");
        btnadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnadd);
        btnadd.setBounds(230, 500, 130, 40);

        btndelete.setBackground(new java.awt.Color(0, 48, 73));
        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 248, 240));
        btndelete.setText("Delete");
        btndelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btndelete);
        btndelete.setBounds(820, 500, 130, 40);

        btnupdate.setBackground(new java.awt.Color(0, 48, 73));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 248, 240));
        btnupdate.setText("Update");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate);
        btnupdate.setBounds(540, 500, 130, 40);

        tablepatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N_ass", "F_name", "B_date", "Genre", "Phone", "Address", "Radio", "Visit_D", "Pourcentage", "Price", "Doctor", "Radiologiste"
            }
        ));
        tablepatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepatient);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(210, 110, 1140, 90);

        combodoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combodoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Doctor 1", "Doctor 2", "Doctor 3", "Doctor 4", " " }));
        combodoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodocActionPerformed(evt);
            }
        });
        jPanel3.add(combodoc);
        combodoc.setBounds(1070, 280, 190, 30);
        jPanel3.add(txtbdate);
        txtbdate.setBounds(310, 380, 190, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Search :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(500, 550, 62, 20);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(580, 80, 440, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("N° assur :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(220, 280, 80, 22);

        txtass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtassActionPerformed(evt);
            }
        });
        txtass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtassKeyPressed(evt);
            }
        });
        jPanel3.add(txtass);
        txtass.setBounds(310, 280, 190, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText(" Radiologiste :");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(940, 330, 120, 22);

        note.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        note.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(note);
        note.setBounds(1070, 380, 280, 100);

        tablecon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N_ass", "F_name", "B_date", "Genre", "Phone", "Address", "Visit_D", "Radio", "Doctor", "Radiologiste", "Note"
            }
        ));
        tablecon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableconMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablecon);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(210, 580, 1140, 110);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("    % :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(240, 430, 50, 14);

        txtpour.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpour.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(txtpour);
        txtpour.setBounds(310, 430, 190, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Price :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(620, 440, 49, 14);

        txtprice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(txtprice);
        txtprice.setBounds(680, 430, 190, 30);

        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });
        jPanel3.add(search1);
        search1.setBounds(570, 550, 440, 30);

        jButton21.setBackground(new java.awt.Color(0, 48, 73));
        jButton21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 248, 240));
        jButton21.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\icons8-impression-40.png")); // NOI18N
        jButton21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21);
        jButton21.setBounds(1230, 50, 130, 50);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Search :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(510, 80, 62, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1370, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        RegistrationD out = new RegistrationD();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PatientlistD out = new PatientlistD();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AdddoctorD dd = new AdddoctorD();
        dd.setLocationRelativeTo(null);
        dd.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DoctorlistD dl = new DoctorlistD();
        dl.setLocationRelativeTo(null);
        dl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        RadiolistD out = new RadiolistD();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Prescription out = new Prescription();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        homed d = new homed();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login out = new Login();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtname.setEditable(true);
        }
        else{

            txtname.setEditable(false);}
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyPressed
        // TODO add your handling code here:
        String pn = txtphone.getText();
        int lenght = pn.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(lenght<10)
            {
                txtphone.setEditable(true);
            }
            else{
                txtphone.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {txtphone.setEditable(true);}
            else{txtphone.setEditable(false);}
        }
    }//GEN-LAST:event_txtphoneKeyPressed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtid.setEditable(false);
        }
        else{
            txtid.setEditable(true);
        }
    }//GEN-LAST:event_txtidKeyPressed

    private void combogenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combogenreActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtass.setText("");
        txtname.setText("");
        txtbdate.setDateFormatString("");
        combogenre.setSelectedItem("Choose");
        txtphone.setText("");
        txtadd.setText("");
        txtvdate.setDateFormatString("");
        comboradio.setSelectedItem("Radio");
        combodoc.setSelectedItem("Doctor");
        comboradiologiste.setSelectedItem("Radiologiste");
        note.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String id = txtid.getText().toString();
        String ass = txtass.getText().toString();
        String name = txtname.getText();
        String bd = txtbdate.getDateFormatString();
        String gen = combogenre.getSelectedItem().toString();
        String ph = txtphone.getText().toString();
        String ad = txtadd.getText();
        String vd = txtvdate.getDateFormatString();
        String rd = comboradio.getSelectedItem().toString();
        String doc = combodoc.getSelectedItem().toString();
        String rdg = comboradiologiste.getSelectedItem().toString();
        String nt = note.getText();
        if(id.equals("")||ass.equals("")||name.equals("")||bd.equals("")|| gen.equals("Choose")||ph.equals("")||ad.equals("")||vd.equals("") ||rd.equals("Radio")||doc.equals("Doctor")||rdg.equals("Radiologiste")||nt.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Some fields are empty check again", "ERROR",1);
        }
        else{
            

            try{
                String sql = "INSERT INTO consult"
                +"(ID,N_ass, F_name, B_date, Genre, Phone, Address, Visit_D,  Radio, Doctor, Radiologiste,Note)"
                +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
                pst = con.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(txtid.getText()));
                pst.setInt(2, Integer.parseInt(txtass.getText()));
                pst.setString(3, txtname.getText());
                pst.setString(4, txtbdate.getDateFormatString());
                pst.setString(5, combogenre.getSelectedItem().toString());
                pst.setInt(6, Integer.parseInt(txtphone.getText()));
                pst.setString(7, txtadd.getText());
                pst.setString(8, txtvdate.getDateFormatString());
                pst.setString(9, comboradio.getSelectedItem().toString());
                pst.setString(10, combodoc.getSelectedItem().toString());
                pst.setString(11, comboradiologiste.getSelectedItem().toString());
                pst.setString(12, note.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "ADD successfully!");

            } catch (HeadlessException | NumberFormatException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            showtable2();
            txtid.setText("");
            txtass.setText("");
            txtname.setText("");
            txtbdate.setDateFormatString("");
            combogenre.setSelectedItem("Choose");
            txtphone.setText("");
            txtadd.setText("");
            txtvdate.setDateFormatString("");
            comboradio.setSelectedItem("Radio");
            combodoc.setSelectedItem("Doctor");
            comboradiologiste.setSelectedItem("Radiologiste");
            note.setText("");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int row = tablecon.getSelectedRow();
        String cell = tablecon.getModel().getValueAt(row, 0).toString();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (choice == JOptionPane.YES_OPTION) {
        String sql= "DELETE FROM consult WHERE ID = " +cell;
        try{
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "DELETED succesfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        showtable2();
        txtid.setText("");
        txtass.setText("");
        txtname.setText("");
        txtbdate.setDateFormatString("");
        combogenre.setSelectedItem("Choose");
        txtphone.setText("");
        txtadd.setText("");
        txtvdate.setDateFormatString("");
        comboradio.setSelectedItem("Radio");
        combodoc.setSelectedItem("Doctor");
        comboradiologiste.setSelectedItem("Radiologiste");
        note.setText("");
        }else {
            System.out.println("Deletion canceled");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablecon.getModel();
        int row = tablecon.getSelectedRow();

        try{
            String sql = "UPDATE consult SET N_ass=?, F_name=?,B_date=?,Genre=?,Phone=?,Address=?,Visit_D=?,Radio=?,Doctor=?,Radiologiste=?,Note=? WHERE ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
            pst = con.prepareStatement(sql);
            pst.setInt(12, Integer.parseInt(txtid.getText()));
            pst.setInt(1, Integer.parseInt(txtass.getText()));
            pst.setString(2, txtname.getText());
            pst.setString(3, txtbdate.getDateFormatString());
            pst.setString(4, combogenre.getSelectedItem().toString());
            pst.setInt(5, Integer.parseInt(txtphone.getText()));
            pst.setString(6, txtadd.getText());
            pst.setString(7, txtvdate.getDateFormatString());
            pst.setString(8, comboradio.getSelectedItem().toString());
            pst.setString(9, combodoc.getSelectedItem().toString());
            pst.setString(10, comboradiologiste.getSelectedItem().toString());
            pst.setString(11, note.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "UPDATED successfully!");

        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        showtable2();
        txtid.setText("");
        txtass.setText("");
        txtname.setText("");
        txtbdate.setDateFormatString("");
        combogenre.setSelectedItem("Choose");
        txtphone.setText("");
        txtadd.setText("");
        txtvdate.setDateFormatString("");
        comboradio.setSelectedItem("Radio");
        combodoc.setSelectedItem("Doctor");
        comboradiologiste.setSelectedItem("Radiologiste");
        note.setText("");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tablepatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepatientMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablepatient.getModel();
        int selectedRowIndex = tablepatient.getSelectedRow();
        txtid.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtass.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtname.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtbdate.setDateFormatString(model.getValueAt(selectedRowIndex, 3).toString());
        combogenre.setSelectedItem(model.getValueAt(selectedRowIndex, 4).toString());
        txtphone.setText(model.getValueAt(selectedRowIndex, 5).toString());
        txtadd.setText(model.getValueAt(selectedRowIndex, 6).toString());
        txtvdate.setDateFormatString(model.getValueAt(selectedRowIndex, 7).toString());
        comboradio.setSelectedItem(model.getValueAt(selectedRowIndex, 8).toString());
        txtpour.setText(model.getValueAt(selectedRowIndex, 9).toString());
        txtprice.setText(model.getValueAt(selectedRowIndex, 10).toString());
        combodoc.setSelectedItem(model.getValueAt(selectedRowIndex, 11).toString());
        comboradiologiste.setSelectedItem(model.getValueAt(selectedRowIndex, 12).toString());
    }//GEN-LAST:event_tablepatientMouseClicked

    private void combodocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combodocActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String searchString = search.getText();
        search(searchString);
    }//GEN-LAST:event_searchKeyReleased

    private void txtassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtassActionPerformed

    private void txtassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtassKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtass.setEditable(false);
        }
        else{
            txtass.setEditable(true);
        }
    }//GEN-LAST:event_txtassKeyPressed

    private void tableconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableconMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tablecon.getModel();
        int selectedRowIndex = tablecon.getSelectedRow();
        txtid.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtass.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtname.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtbdate.setDateFormatString(model.getValueAt(selectedRowIndex, 3).toString());
        combogenre.setSelectedItem(model.getValueAt(selectedRowIndex, 4).toString());
        txtphone.setText(model.getValueAt(selectedRowIndex, 5).toString());
        txtadd.setText(model.getValueAt(selectedRowIndex, 6).toString());
        txtvdate.setDateFormatString(model.getValueAt(selectedRowIndex, 7).toString());
        comboradio.setSelectedItem(model.getValueAt(selectedRowIndex, 8).toString());
        combodoc.setSelectedItem(model.getValueAt(selectedRowIndex, 9).toString());
        comboradiologiste.setSelectedItem(model.getValueAt(selectedRowIndex, 10).toString());
        note.setText(model.getValueAt(selectedRowIndex, 11).toString());
    }//GEN-LAST:event_tableconMouseClicked

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased
        // TODO add your handling code here:
        String searchString = search1.getText();
        search2(searchString);
    }//GEN-LAST:event_search1KeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         ConsultationD cn = new ConsultationD();
        cn.setLocationRelativeTo(null);
        cn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
            String report = "C:\\Users\\TAHAR\\JaspersoftWorkspace\\consult\\consult.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);

            System.out.print("connexion bien reussé");

            JasperPrint jp= JasperFillManager.fillReport(jr, null,con);
            System.out.print("connexion bien reussé");
            JasperViewer jv = new JasperViewer(jp, true);
            System.out.print("connexion bien reussé");
            jv.viewReport(jp, false);
            System.out.print("connexion bien reussé");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ConsultationD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultationD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(ConsultationD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton21ActionPerformed
 public void showtable(){
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    String sql = "SELECT * FROM patient";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    tablepatient.setModel(DbUtils.resultSetToTableModel(rs));
    
    
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null, ex);
    }
    
    }
 public void showtable2(){
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    String sql = "SELECT * FROM consult";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    tablecon.setModel(DbUtils.resultSetToTableModel(rs));
    
    
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null, ex);
    }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultationD fenetre = new ConsultationD();
               //set titel
        fenetre.setTitle("Consultation");
        //nous demandons mtn a notre objet de se positionner au centre
        fenetre.setLocationRelativeTo(null);
        //termine le processus lorsqu'on clique sur la croix rouge
        fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenetre.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel cnaspic;
    private javax.swing.JComboBox<String> combodoc;
    private javax.swing.JComboBox<String> combogenre;
    private javax.swing.JComboBox<String> comboradio;
    private javax.swing.JComboBox<String> comboradiologiste;
    private javax.swing.JLabel dated;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField note;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JTable tablecon;
    private javax.swing.JTable tablepatient;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtass;
    private com.toedter.calendar.JDateChooser txtbdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtpour;
    private javax.swing.JTextField txtprice;
    private com.toedter.calendar.JDateChooser txtvdate;
    // End of variables declaration//GEN-END:variables
}
