/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centreimagerie;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author TAHAR
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    Connection con ;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        combox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        txtuser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtuser.setBorder(null);
        getContentPane().add(txtuser);
        txtuser.setBounds(600, 280, 210, 30);

        txtpass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtpass.setBorder(null);
        getContentPane().add(txtpass);
        txtpass.setBounds(600, 350, 210, 30);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(600, 310, 210, 10);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(600, 380, 210, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\utilisateur.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 280, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\cadenas.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 350, 24, 24);

        jButton1.setBackground(new java.awt.Color(0, 11, 50));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 480, 90, 40);

        jButton2.setBackground(new java.awt.Color(0, 11, 50));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 480, 90, 40);

        combox.setBackground(new java.awt.Color(0, 11, 50));
        combox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        combox.setForeground(new java.awt.Color(255, 255, 255));
        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Doctor", "Technician", "Reception" }));
        combox.setBorder(null);
        getContentPane().add(combox);
        combox.setBounds(600, 200, 210, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\1_20230301_110706_0000.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Reset code:
        txtuser.setText("");
        txtpass.setText("");
        combox.setSelectedItem("Select");
    }//GEN-LAST:event_jButton2ActionPerformed
      
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Login code:
        String usrname = txtuser.getText();
        String pass = txtpass.getText();
        String option = combox.getSelectedItem().toString();
        if(usrname.equals("")||pass.equals("")||option.equals("Select"))
        {
        JOptionPane.showMessageDialog(rootPane, "Some fields are empty check again!", "Error",1);
        }
        else{
        try{
        con = Centreimagerie.getConnection();
        pst = con.prepareStatement("SELECT * FROM clogin WHERE username=? AND password=?");
        pst.setString(1, usrname);
        pst.setString(2, pass);
        rs = pst.executeQuery();
        if(rs.next())
        {
        String s1 = rs.getString("options");
        String un = rs.getString("username");
        if(option.equalsIgnoreCase("Admin")&& un.equalsIgnoreCase("admin"))
        {
        Admin ad = new Admin();
        ad.setVisible(true);
        dispose();
        }
        if(option.equalsIgnoreCase("Doctor")&& un.equalsIgnoreCase("doctor"))
        {
        homed hd = new homed();
        hd.setVisible(true);
        dispose();
        }
        if(option.equalsIgnoreCase("Technician")&& un.equalsIgnoreCase("tech"))
        {
        homet ht = new homet();
        ht.setVisible(true);
        dispose();
        }
        if(option.equalsIgnoreCase("Reception")&& un.equalsIgnoreCase("recep"))
        {
        homer hr = new homer();
        hr.setVisible(true);
        dispose();
        }
        }
        else{
        JOptionPane.showMessageDialog(rootPane, "Username or Password not matched try again!","Error",1 );
        txtuser.setText("");
        txtpass.setText("");
        combox.setSelectedItem("Select");
        }
        }
        catch(Exception ex)
        { System.out.println(""+ex);}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login fenetre = new Login();
                //set titel
        fenetre.setTitle("Login");
        //set mesure: 
        fenetre.setSize(1000, 600);
        //nous demandons mtn a notre objet de se positionner au centre
        fenetre.setLocationRelativeTo(null);
        //termine le processus lorsqu'on clique sur la croix rouge
        fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenetre.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
