/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centreimagerie;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author TAHAR
 */
public class RadiolistD extends javax.swing.JFrame {
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form RadiolistD
     */
    public RadiolistD() {
        initComponents();
        setExtendedState(RadiolistD.MAXIMIZED_BOTH);
        dt();
        showtable();
    }
public void dt()
    {
    Date d = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String dd=sdf.format(d);
    dater.setText(dd);
    }
    
    public void setRecords(){
        DefaultTableModel model = (DefaultTableModel) tableradio.getModel();
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    PreparedStatement pst = con.prepareStatement("SELECT * FROM radio");
    ResultSet rs = pst.executeQuery();
    
    while(rs.next())
    {
    String id = rs.getString("ID");
    String nom = rs.getString("Name"); 
    String pri = rs.getString("Price");
   
    Object[] obj = {id, nom, pri};
    model = (DefaultTableModel)tableradio.getModel();
    model.addRow(obj);
    }
    
    } catch (SQLException ex) {
        Logger.getLogger(RegistrationR.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }
    public void search(String str){
        DefaultTableModel model = (DefaultTableModel) tableradio.getModel();
    model = (DefaultTableModel) tableradio.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    tableradio.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        cnaspic1 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        dater1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableradio = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btndelete1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        cnaspic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dater = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1373, 710));
        setMinimumSize(new java.awt.Dimension(1373, 710));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 248, 240));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 48, 73));
        jPanel4.setMaximumSize(new java.awt.Dimension(185, 710));
        jPanel4.setMinimumSize(new java.awt.Dimension(185, 710));
        jPanel4.setLayout(null);

        jButton10.setBackground(new java.awt.Color(0, 48, 73));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 248, 240));
        jButton10.setText("Log out");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);
        jButton10.setBounds(30, 530, 130, 40);

        jButton11.setBackground(new java.awt.Color(0, 48, 73));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 248, 240));
        jButton11.setText("Home page");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);
        jButton11.setBounds(30, 480, 130, 40);

        jButton12.setBackground(new java.awt.Color(0, 48, 73));
        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 248, 240));
        jButton12.setText("Registration");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(30, 130, 130, 40);

        jButton13.setBackground(new java.awt.Color(0, 48, 73));
        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 248, 240));
        jButton13.setText("Patients list");
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);
        jButton13.setBounds(30, 180, 130, 40);

        jButton14.setBackground(new java.awt.Color(0, 48, 73));
        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 248, 240));
        jButton14.setText("Add doctors");
        jButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14);
        jButton14.setBounds(30, 230, 130, 40);

        jButton15.setBackground(new java.awt.Color(0, 48, 73));
        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 248, 240));
        jButton15.setText("Doctors list");
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15);
        jButton15.setBounds(30, 280, 130, 40);

        jButton16.setBackground(new java.awt.Color(0, 48, 73));
        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 248, 240));
        jButton16.setText("Radios ");
        jButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16);
        jButton16.setBounds(30, 330, 130, 40);

        cnaspic1.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\aaa.png")); // NOI18N
        jPanel4.add(cnaspic1);
        cnaspic1.setBounds(20, 20, 130, 80);

        jButton18.setBackground(new java.awt.Color(0, 48, 73));
        jButton18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 248, 240));
        jButton18.setText("Prescription");
        jButton18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton18);
        jButton18.setBounds(30, 380, 130, 40);

        jButton20.setBackground(new java.awt.Color(0, 48, 73));
        jButton20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 248, 240));
        jButton20.setText("Consultation");
        jButton20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton20);
        jButton20.setBounds(30, 430, 130, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 185, 710);

        jPanel5.setBackground(new java.awt.Color(0, 48, 73));
        jPanel5.setMaximumSize(new java.awt.Dimension(1380, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(1380, 40));
        jPanel5.setLayout(null);

        dater1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dater1.setForeground(new java.awt.Color(255, 248, 240));
        jPanel5.add(dater1);
        dater1.setBounds(1280, 0, 90, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 248, 240));
        jLabel5.setText("Radio");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(750, 0, 100, 40);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 1380, 40);

        tableradio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tableradio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "Dental Panoramic ", "37.5"},
                {"002", "Telemetry", "200A/100E"},
                {"003", "BACCARA-Lambar spine", "50"},
                {"004", "BACCARA-Cervical spine", "50"},
                {"005", "BACCARA-Dorsal spine", "50"},
                {"006", "BACCARA-ASP", "25"},
                {"007", "BACCARA-Pool", "25"},
                {"008", "BACCARA-Knee in charge", "50"},
                {"009", "OS.P-Teletorax", "50"},
                {"010", "OS.P-Wrist", "25"},
                {"011", "OS.P-Hand", "25"},
                {"012", "OS.P-Fingers", "25"},
                {"013", "OS.P-Upper arm", "25"},
                {"014", "OS.P-Shoulder", "20"},
                {"015", "OS.P-Haunch", "35"},
                {"016", "OS.P-Femur", "35"},
                {"017", "OS.P-Knee", "35"},
                {"018", "OS.P-Leg", "35"},
                {"019", "OS.P-Ankle", "35"},
                {"020", "OS.P-Foot", "35"},
                {"021", "OS.P-Toes", "35"},
                {"022", "OS.P-Head", "50"},
                {"023", "Sinus(NMP/NFP)", "50"}
            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        tableradio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableradioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableradio);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 130, 760, 330);

        btnadd.setBackground(new java.awt.Color(0, 48, 73));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 248, 240));
        btnadd.setText("Add");
        btnadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd);
        btnadd.setBounds(290, 600, 130, 40);

        btnupdate.setBackground(new java.awt.Color(0, 48, 73));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 248, 240));
        btnupdate.setText("Update");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(570, 600, 130, 40);

        btnreset.setBackground(new java.awt.Color(0, 48, 73));
        btnreset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 248, 240));
        btnreset.setText("Reset");
        btnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset);
        btnreset.setBounds(1130, 600, 130, 40);

        jButton19.setBackground(new java.awt.Color(0, 48, 73));
        jButton19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 248, 240));
        jButton19.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\icons8-impression-40.png")); // NOI18N
        jButton19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(1230, 50, 130, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 500, 50, 22);

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid);
        txtid.setBounds(300, 500, 190, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 500, 70, 22);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(690, 500, 190, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Price :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1030, 504, 49, 20);

        txtprice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtprice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtprice);
        txtprice.setBounds(1100, 500, 190, 30);

        btndelete1.setBackground(new java.awt.Color(0, 48, 73));
        btndelete1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndelete1.setForeground(new java.awt.Color(255, 248, 240));
        btndelete1.setText("Delete");
        btndelete1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete1);
        btndelete1.setBounds(840, 600, 130, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Search :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(500, 90, 62, 20);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(600, 80, 440, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 710);

        jPanel3.setBackground(new java.awt.Color(0, 48, 73));
        jPanel3.setMaximumSize(new java.awt.Dimension(185, 710));
        jPanel3.setMinimumSize(new java.awt.Dimension(185, 710));
        jPanel3.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 48, 73));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 248, 240));
        jButton1.setText("Prescription");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(30, 380, 130, 40);

        jButton2.setBackground(new java.awt.Color(0, 48, 73));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 248, 240));
        jButton2.setText("Log out");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(30, 650, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 48, 73));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 248, 240));
        jButton3.setText("Home page");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(30, 600, 130, 40);

        jButton5.setBackground(new java.awt.Color(0, 48, 73));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 248, 240));
        jButton5.setText("Patients list");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(30, 180, 130, 40);

        jButton6.setBackground(new java.awt.Color(0, 48, 73));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 248, 240));
        jButton6.setText("Add doctor");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(30, 230, 130, 40);

        jButton7.setBackground(new java.awt.Color(0, 48, 73));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 248, 240));
        jButton7.setText("Doctors list");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(30, 280, 130, 40);

        jButton8.setBackground(new java.awt.Color(0, 48, 73));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 248, 240));
        jButton8.setText("Radios list");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(30, 330, 130, 40);

        jButton9.setBackground(new java.awt.Color(0, 48, 73));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 248, 240));
        jButton9.setText("Registration");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73), new java.awt.Color(0, 48, 73)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(30, 130, 130, 40);

        cnaspic.setIcon(new javax.swing.ImageIcon("D:\\01 Disque C\\L3 INFO\\tpihm22\\aaa.png")); // NOI18N
        jPanel3.add(cnaspic);
        cnaspic.setBounds(20, 20, 120, 80);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 185, 710);

        jPanel2.setBackground(new java.awt.Color(0, 48, 73));
        jPanel2.setMaximumSize(new java.awt.Dimension(1380, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(1380, 40));
        jPanel2.setLayout(null);

        dater.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dater.setForeground(new java.awt.Color(255, 248, 240));
        jPanel2.add(dater);
        dater.setBounds(1280, 0, 90, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 248, 240));
        jLabel1.setText("Doctor's list");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(730, 0, 130, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1380, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Prescription out = new Prescription();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login out = new Login();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        homed out = new homed();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PatientlistD list = new PatientlistD();
        list.setLocationRelativeTo(null);
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AdddoctorD out = new AdddoctorD();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DoctorlistD dc = new DoctorlistD();
        dc.setLocationRelativeTo(null);
        dc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        RadiolistD out = new RadiolistD();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        RegistrationD out = new RegistrationD();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Login out = new Login();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        homer out = new homer();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        RegistrationR go = new RegistrationR();
        go.setLocationRelativeTo(null);
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        PatientlistR list = new PatientlistR();
        list.setLocationRelativeTo(null);
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        AdddoctorR out = new AdddoctorR();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        DoctorlistR out = new DoctorlistR();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        Prescription out = new Prescription();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void tableradioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableradioMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableradio.getModel();
        int selectedRowIndex = tableradio.getSelectedRow();
        txtid.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtprice.setText(model.getValueAt(selectedRowIndex, 2).toString());

    }//GEN-LAST:event_tableradioMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String id = txtid.getText().toString();
        String name = txtname.getText();
        String pr = txtprice.getText().toString();
        try{
            String sql = "INSERT INTO radio"
            +"(ID, Name, Price)"
            +"VALUES (?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
            pst = con.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txtid.getText()));
            pst.setString(2, txtname.getText());
            pst.setInt(3, Integer.parseInt(txtprice.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "ADD successfully!");

        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        showtable();
        txtid.setText("");
        txtname.setText("");
        txtprice.setText("");

    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableradio.getModel();
        int row = tableradio.getSelectedRow();

        try{
            String sql = "UPDATE radio SET Name=?,Price=? WHERE ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
            pst = con.prepareStatement(sql);
            pst.setInt(3, Integer.parseInt(txtid.getText()));
            pst.setString(1, txtname.getText());
            pst.setString(2, txtprice.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "UPDATED successfully!");

        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        showtable();
        txtid.setText("");
        txtname.setText("");
        txtprice.setText("");

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtname.setText("");
        txtprice.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        // TODO add your handling code here:
        int row = tableradio.getSelectedRow();
        String cell = tableradio.getModel().getValueAt(row, 0).toString();
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (choice == JOptionPane.YES_OPTION) {
        String sql= "DELETE FROM radio WHERE ID = " +cell;
        try{
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "DELETED succesfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        showtable();
        txtid.setText("");
        txtname.setText("");
        txtprice.setText("");
        }else {
            System.out.println("Deletion canceled");
        }
    }//GEN-LAST:event_btndelete1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String searchString = search.getText();
        search(searchString);
    }//GEN-LAST:event_searchKeyReleased

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
          String report = "C:\\Users\\TAHAR\\JaspersoftWorkspace\\radiolist\\radiolist.jrxml";  
   JasperReport jr = JasperCompileManager.compileReport(report);  
   

   System.out.print("connexion bien reussé");
   
            JasperPrint jp= JasperFillManager.fillReport(jr, null,con);
            System.out.print("connexion bien reussé");
            JasperViewer jv = new JasperViewer(jp, true);
            System.out.print("connexion bien reussé");
            jv.viewReport(jp, false);
            System.out.print("connexion bien reussé");
        } catch (ClassNotFoundException ex) { 
        Logger.getLogger(RadiolistD.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(RadiolistD.class.getName()).log(Level.SEVERE, null, ex);
    } catch (JRException ex) {
        Logger.getLogger(RadiolistD.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        ConsultationD cn = new ConsultationD();
        cn.setLocationRelativeTo(null);
        cn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton20ActionPerformed
public void showtable(){
    try{
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/centredb","root","");
    String sql = "SELECT * FROM radio";
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    tableradio.setModel(DbUtils.resultSetToTableModel(rs));
    
    
    } catch (SQLException ex) {
       JOptionPane.showMessageDialog(null, ex);
    }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadiolistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadiolistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadiolistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadiolistD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RadiolistD fenetre = new RadiolistD();
               //set titel
        fenetre.setTitle("Radio");
        //nous demandons mtn a notre objet de se positionner au centre
        fenetre.setLocationRelativeTo(null);
        //termine le processus lorsqu'on clique sur la croix rouge
        fenetre.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fenetre.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel cnaspic;
    private javax.swing.JLabel cnaspic1;
    private javax.swing.JLabel dater;
    private javax.swing.JLabel dater1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTable tableradio;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
